export enum IncomeType {
  OVERTIME = 'OVERTIME',
  CASUAL = 'CASUAL',
  CONTRACT_VARIABLE = 'CONTRACT_VARIABLE',
  COMMISSIONS = 'COMMISSIONS',
  BONUS = 'BONUS',
  INVESTMENT_SHARES = 'INVESTMENT_SHARES',
  INVESTMENT_INTEREST = 'INVESTMENT_INTEREST',
} 