export enum VerificationMethod {
  NON_ESSENTIAL_SERVICES = 'NON_ESSENTIAL_SERVICES',
  ESSENTIAL_SERVICES = 'ESSENTIAL_SERVICES',
  ONE_YEAR_VERIFICATION = 'ONE_YEAR_VERIFICATION',
  TWO_YEAR_VERIFICATION = 'TWO_YEAR_VERIFICATION',
} 